apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/pv001"
