mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "32000:3306"
  environment:
      MYSQL_ROOT_PASSWORD: password
redis:
  image: redis:latest
  container_name: redis
web:
  build: .
  ports:
   - "8001:8001"
  links:
   - redis:redis
   - mysql:mysql
